### PR TITLE
Homepage last finishes

### PR DESCRIPTION
**Pull request by Tippe**
Added styling to home page
Added USP's with icons
Linked correct images (images/dienst_1) etc...
Added some comments and corrected comments in style.css

### CODE REVIEW

**Review by Mingull — CHANGES_REQUESTED** [review]
There is a random quotation mark above the header

Tip: Look in the head

**Review by Mingull — DISMISSED** [review]
Nice

**Comment by Tippe** [comment]
> Nice

Was ff zoeken ik dacht "wtf bedoel jij" maar vond em

**Review by KanekiEyepatch — APPROVED** [review]
Toppie

**Pull request merged**
